using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using AutoMapper;
using MovieBase.Dtos;
using MovieBase.Models;

namespace MovieBase.Controllers.API {
    public class CustomersController : ApiController {
        // Used to access the database for this class.
        private ApplicationDbContext _context;

        public CustomersController() {
            // Initialized upon calling this controller during run-time.
            _context = new ApplicationDbContext();
        }

        // GET /api/customers
        public IEnumerable<CustomerDto> GetCustomers() {
            // Returns a list of objects (customers) & uses Mapper to utilize CustomerDto.
            return _context.Customers.ToList().Select(Mapper.Map<Customer, CustomerDto>);
        }

        // GET /api/customers/1
        public CustomerDto GetCustomer(int id) {
            // Returns one object (customer) by using a matching id.
            Customer customer = _context.Customers.SingleOrDefault(c => c.Id == id);
            // If there's no customer, return the standard not found http response.
            if (customer == null) throw new HttpResponseException(HttpStatusCode.NotFound);
            // Otherwise return the customer via the Mapper method.
            return Mapper.Map<Customer, CustomerDto>(customer);
        }

        // POST /api/customers
        [HttpPost]
        public CustomerDto CreateCustomer(CustomerDto customerDto) {
            // Changes the program's flow via using validation data or return an error.
            if (!ModelState.IsValid) throw new HttpResponseException(HttpStatusCode.BadRequest);

            // Maps CustomerDto to the Customer class before touching the database.
            Customer customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            // Adds it to dbContext before saving it to the database. Finally return customer.
            _context.Customers.Add(customer);
            _context.SaveChanges();

            // Copies over the id generated by the database for customer.
            customerDto.Id = customer.Id;

            return customerDto;
        }

        // PUT /api/customers/1
        [HttpPut]
        public void UpdateCustomer(int id, CustomerDto customerDto) {
            // Changes the program's flow via using validation data or return an error.
            if (!ModelState.IsValid) throw new HttpResponseException(HttpStatusCode.BadRequest);
            // Returns one object (customer) by using a matching id.
            Customer customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);
            // If there's no customer, return the standard not found http response.
            if (customerInDb == null) throw new HttpResponseException(HttpStatusCode.NotFound);

            // Maps the customer Dto variant to the customer's database variant.
            Mapper.Map(customerDto, customerInDb);
            // Saves the changes to the database.
            _context.SaveChanges();
        }

        // DELETE /api/customers/1
        [HttpDelete]
        public void DeleteCustomer(int id) {
            // Returns one object (customer) by using a matching id.
            Customer customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);
            // If there's no customer, return the standard not found http response.
            if (customerInDb == null) throw new HttpResponseException(HttpStatusCode.NotFound);

            // Delete the customer & saves the changes to the database.
            _context.Customers.Remove(customerInDb);
            _context.SaveChanges();
        }
    }
}